@startuml
left to right direction

actor "Buyer" as Buyer
actor "Seller" as Seller
actor "Payment Gateway" as PaymentGateway
actor "Shipping Company" as ShippingCompany

rectangle "G2U" {
    usecase "Create/Update\n Account Info" as AccountInfo
    usecase "View\n My Purchases" as MyPurchases
    usecase "View\n Liked Products" as LikedProducts
    usecase "Browse\n Products" as BrowseProducts
    usecase "Filter\n Products" as FilterProducts
    usecase "Manage\n Posts" as ManagePosts
    usecase "Post\n Products" as PostProducts
    usecase "Update/Delete\n Products" as UpdateDeleteProducts
    usecase "Order System" as OrderSystem
    usecase "Payment" as Payment
    usecase "Shipping\n Status" as ShippingStatus
}

Buyer --> AccountInfo : "Provide\n Buyer's Credentials"
Seller --> AccountInfo : "Provide\n Seller's Credentials"

Buyer --> BrowseProducts : "Access Product List"
BrowseProducts --> FilterProducts : "Apply Filters"

Buyer --> MyPurchases : "View Purchase History"
Buyer --> LikedProducts : "Access Liked Products"

Buyer --> ManagePosts : "Show interest\n to buy the\n product"
Seller --> ManagePosts : "Access\n Manage Posts"

ManagePosts --> PostProducts : "Add Product\n to Sell/Buy"
ManagePosts --> UpdateDeleteProducts : "Modify/Delete\n Product Post"

Buyer --> OrderSystem : "Order Product"
OrderSystem --> Seller : "Notify Seller of Order"

OrderSystem --> Payment : "Initiate Payment"
Payment --> PaymentGateway : "Process Payment"

OrderSystem --> ShippingStatus : "Request\n Shipping Update"
ShippingStatus --> ShippingCompany : "Track/Update\n Shipping"

ShippingCompany --> Buyer : "Provide\n Shipping Details"
ShippingCompany --> Seller : "Notify\n Seller of Shipping Status"
@enduml

